name: Tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - uses: actions/cache@v1
      id: cache
      with:
        path: /usr/lib/python3/
        key: ${{ hashFiles('**/requirements.txt') }}-python-cache
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r tests/requirements.txt flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 crawlai --count --ignore=W191,E101,E126,E128,W503 --max-complexity=6 --max-line-length=80 --statistics
    - name: Test with pytest
      run: PYTHONPATH=. pytest tests/
